# -*- coding: utf-8 -*-
"""Copy of DP:autoFAQ.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OL-h0sB7xf3po7v9FYqSKcfIad4cUEC5
"""

pip install -q deeppavlov

# Commented out IPython magic to ensure Python compatibility.
# %load https://raw.githubusercontent.com/deepmipt/DeepPavlov/master/deeppavlov/configs/faq/tfidf_logreg_en_faq.json

!python -m deeppavlov install tfidf_logreg_en_faq

!python -m deeppavlov interact tfidf_logreg_en_faq -d

pip install deeppavlov

pip install git+https://github.com/deepmipt/bert.git@feat/multi_gpu

pip install bert_dp

from deeppavlov import build_model, configs

model = build_model(configs.squad.squad_ru_bert, download=True)
model(['Борис видит как люди видят красоту ходят направо  налево прямо  назад. '], ['Что видит Борис?'])